//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiExamples.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class datatables_demo
    {
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string position { get; set; }
        public string email { get; set; }
        public string office { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<int> salary { get; set; }
        public Nullable<int> seq { get; set; }
        public string extn { get; set; }
    }
}
