//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiExamples.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.positions = new HashSet<position>();
            this.SWS_entries = new HashSet<SWS_entries>();
        }
    
        public double EDW_PERS_ID { get; set; }
        public string FULLNAME { get; set; }
        public Nullable<double> YR_OF_SVC { get; set; }
        public Nullable<System.DateTime> UNIV_START_DATE { get; set; }
        public Nullable<System.DateTime> LIBRARY_START_DATE { get; set; }
        public string UIN { get; set; }
        public string NETID { get; set; }
        public string NETID_DOMAIN { get; set; }
        public string RACE_ALT { get; set; }
        public Nullable<System.DateTime> BIRTH_DT { get; set; }
        public string GENDER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<position> positions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SWS_entries> SWS_entries { get; set; }
    }
}
