//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiExamples.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class position
    {
        public int posid { get; set; }
        public Nullable<double> EDW_PERS_ID { get; set; }
        public string EMPEE_CLS_CD { get; set; }
        public string EMPEE_CLS_LONG_DESC { get; set; }
        public Nullable<double> FAC_TENURE_TRACK_YR { get; set; }
        public string FAC_RANK_CD { get; set; }
        public string POSN_NBR { get; set; }
        public string JOB_DETL_TITLE { get; set; }
        public Nullable<System.DateTime> JOB_DETL_EFF_DT { get; set; }
        public Nullable<System.DateTime> JOB_DETL_DATA_EXP_DT { get; set; }
        public string ORG_CD { get; set; }
        public string JOB_DETL_SUB_DEPT_LEVEL_6_NAME { get; set; }
        public string JOB_DETL_SUB_DEPT_LEVEL_7_NAME { get; set; }
        public string PAPE_CIV_SVC_ID { get; set; }
        public string POSN_EXEMPT_IND { get; set; }
        public Nullable<double> JOB_DETL_FTE { get; set; }
        public Nullable<double> JOB_DETL_ANNL_SAL { get; set; }
        public string JOB_PROBN_BGN_DT { get; set; }
        public string JOB_PROBN_END_DT { get; set; }
        public string JOB_DETL_STATUS_DESC { get; set; }
        public string DIV { get; set; }
        public string EMPEE_CLS_CD_1 { get; set; }
        public Nullable<System.DateTime> EMPEE_CLS_HIST_EFF_DT { get; set; }
        public Nullable<System.DateTime> EMPEE_CLS_EXP_DT { get; set; }
        public string EMPEE_CLS_CUR_INFO_IND { get; set; }
        public string EMPEE_CLS_SHORT_DESC { get; set; }
        public string EMPEE_CLS_LONG_DESC_1 { get; set; }
        public string PAYR_ID { get; set; }
        public string EMPEE_CLS_PAYR_ID_DESC { get; set; }
        public Nullable<double> EMPEE_CLS_DFLT_HOURS_DAY { get; set; }
        public Nullable<double> EMPEE_CLS_DFLT_HOURS_PAY { get; set; }
        public string EMPEE_CLS_SAL_DESC { get; set; }
        public string LEAVE_CATGRY_CD { get; set; }
        public string LEAVE_CATGRY_DESC { get; set; }
        public string BNFT_CATGRY_CD { get; set; }
        public string BNFT_CATGRY_DESC { get; set; }
        public string EEO_CNTRCT_GROUP_CD { get; set; }
        public string EEO_CNTRCT_GROUP_DESC { get; set; }
        public string EEO_INSTRN_DESC { get; set; }
        public string WORK_PERD_CD { get; set; }
        public string WORK_PERD_DESC { get; set; }
        public string FLSA_IND { get; set; }
        public string EMPEE_GROUP_CD { get; set; }
        public string EMPEE_GROUP_DESC { get; set; }
        public string LEAVE_REQUEST_IND { get; set; }
        public Nullable<double> POSN_BUDG_BASIS { get; set; }
        public Nullable<double> POSN_ANNL_BASIS { get; set; }
        public Nullable<System.DateTime> EMPEE_CLS_HIST_POST_DT { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
