//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiExamples.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SWS_entries
    {
        public string evalId { get; set; }
        public double EDW_PERS_ID { get; set; }
        public int FY { get; set; }
        public string FRCScore { get; set; }
        public string FRCVariable { get; set; }
        public Nullable<double> MeritIncrease { get; set; }
        public Nullable<double> EquityAdjust { get; set; }
        public Nullable<double> P_T { get; set; }
        public Nullable<double> EvalScore { get; set; }
        public Nullable<double> Stipend { get; set; }
        public Nullable<double> Other { get; set; }
        public string Notes { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
