//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiExamples.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.accesses = new HashSet<access>();
            this.depts = new HashSet<dept>();
            this.files = new HashSet<file>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string phone { get; set; }
        public string city { get; set; }
        public string zip { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<System.DateTime> registered_date { get; set; }
        public Nullable<bool> active { get; set; }
        public string comments { get; set; }
        public Nullable<int> manager { get; set; }
        public Nullable<int> site { get; set; }
        public Nullable<int> image { get; set; }
        public Nullable<System.TimeSpan> shift_start { get; set; }
        public Nullable<System.TimeSpan> shift_end { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<access> accesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dept> depts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<file> files { get; set; }
    }
}
