//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace herman_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class actor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public actor()
        {
            this.actor2movie = new HashSet<actor2movie>();
        }
    
        public int actor_id { get; set; }
        public string actor_first_name { get; set; }
        public string actor_mi { get; set; }
        public string actor_last_name { get; set; }
        public string actor_suffix { get; set; }
        public string actor_photo { get; set; }
        public Nullable<bool> featured { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<actor2movie> actor2movie { get; set; }
    }
}
