//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace herman_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class character
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public character()
        {
            this.actor2movie = new HashSet<actor2movie>();
        }
    
        public int char_id { get; set; }
        public string char_first_name { get; set; }
        public string char_mi { get; set; }
        public string char_last_name { get; set; }
        public string char_alias { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
        public string char_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<actor2movie> actor2movie { get; set; }
    }
}
