//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace herman_v2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actor2movie> actor2movie { get; set; }
        public virtual DbSet<actor> actors { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<character> characters { get; set; }
        public virtual DbSet<director> directors { get; set; }
        public virtual DbSet<image> images { get; set; }
        public virtual DbSet<Video> Videos { get; set; }
        public virtual DbSet<top5s> top5s { get; set; }
    }
}
