//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace herman_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class top5s
    {
        public int actor_id { get; set; }
        public string actor_first_name { get; set; }
        public string actor_last_name { get; set; }
        public Nullable<int> cnt { get; set; }
    }
}
