//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace herman_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Video()
        {
            this.actor2movie = new HashSet<actor2movie>();
            this.images = new HashSet<image>();
        }
    
        public int video_id { get; set; }
        public string Video_Name { get; set; }
        public Nullable<bool> VHS { get; set; }
        public Nullable<bool> DVD { get; set; }
        public Nullable<bool> BLURAY { get; set; }
        public Nullable<bool> DIGITAL { get; set; }
        public Nullable<int> Director { get; set; }
        public Nullable<int> Release_Date { get; set; }
        public Nullable<int> length { get; set; }
        public Nullable<int> rating { get; set; }
        public Nullable<int> Category { get; set; }
        public string Plot { get; set; }
        public string Tagline { get; set; }
        public string Box_Cover { get; set; }
        public Nullable<bool> featured { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string owner { get; set; }
        public string keywords { get; set; }
        public string imdb_id { get; set; }
        public string tmdb_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<actor2movie> actor2movie { get; set; }
        public virtual category category1 { get; set; }
        public virtual director director1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<image> images { get; set; }
    }
}
